# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parameters_1st_tab_v2.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(800, 600))
        Dialog.setMaximumSize(QtCore.QSize(800, 600))

        regExp = QtCore.QRegExp("[-]{0,1}\d{0,}\.\d{0,}")  # Валидатор на ввод только чисел и точки(используется для полей ввода)
        validator = QtGui.QRegExpValidator(regExp)

        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.rc = QtWidgets.QLineEdit(self.tab)
        self.rc.setMinimumSize(QtCore.QSize(400, 30))
        self.rc.setMaximumSize(QtCore.QSize(400, 30))
        self.rc.setObjectName("rc")
        self.rc.setValidator(validator)
        self.horizontalLayout.addWidget(self.rc)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.length = QtWidgets.QLineEdit(self.tab)
        self.length.setMinimumSize(QtCore.QSize(400, 30))
        self.length.setMaximumSize(QtCore.QSize(400, 30))
        self.length.setObjectName("porosity")
        self.length.setValidator(validator)
        self.horizontalLayout_3.addWidget(self.length)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.B_liq = QtWidgets.QLineEdit(self.tab_2)
        self.B_liq.setMinimumSize(QtCore.QSize(400, 30))
        self.B_liq.setMaximumSize(QtCore.QSize(400, 30))
        self.B_liq.setObjectName("B_liq")
        self.B_liq.setValidator(validator)
        self.horizontalLayout_4.addWidget(self.B_liq)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setMinimumSize(QtCore.QSize(0, 30))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.mu = QtWidgets.QLineEdit(self.tab_2)
        self.mu.setMinimumSize(QtCore.QSize(400, 30))
        self.mu.setMaximumSize(QtCore.QSize(400, 30))
        self.mu.setObjectName("mu")
        self.mu.setValidator(validator)
        self.horizontalLayout_6.addWidget(self.mu)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_51 = QtWidgets.QLabel(self.tab_3)
        self.label_51.setMinimumSize(QtCore.QSize(0, 30))
        self.label_51.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_27.addWidget(self.label_51)
        self.h_eff = QtWidgets.QLineEdit(self.tab_3)
        self.h_eff.setMinimumSize(QtCore.QSize(400, 30))
        self.h_eff.setMaximumSize(QtCore.QSize(400, 30))
        self.h_eff.setObjectName("h_eff")
        self.h_eff.setValidator(validator)
        self.horizontalLayout_27.addWidget(self.h_eff)
        self.label_52 = QtWidgets.QLabel(self.tab_3)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_27.addWidget(self.label_52)
        self.verticalLayout_5.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setMinimumSize(QtCore.QSize(0, 30))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.K = QtWidgets.QLineEdit(self.tab_3)
        self.K.setMinimumSize(QtCore.QSize(400, 30))
        self.K.setMaximumSize(QtCore.QSize(400, 30))
        self.K.setObjectName("K")
        self.K.setValidator(validator)
        self.horizontalLayout_8.addWidget(self.K)
        self.Skin = QtWidgets.QLabel(self.tab_3)
        self.Skin.setObjectName("Skin")
        self.horizontalLayout_8.addWidget(self.Skin)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setMinimumSize(QtCore.QSize(0, 30))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_9.addWidget(self.label_15)
        self.kv_kh = QtWidgets.QLineEdit(self.tab_3)
        self.kv_kh.setMinimumSize(QtCore.QSize(400, 30))
        self.kv_kh.setMaximumSize(QtCore.QSize(400, 30))
        self.kv_kh.setObjectName("kv_kh")
        self.kv_kh.setValidator(validator)
        self.horizontalLayout_9.addWidget(self.kv_kh)
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_9.addWidget(self.label_16)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setMinimumSize(QtCore.QSize(0, 30))
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_13.addWidget(self.label_23)
        self.C_t = QtWidgets.QLineEdit(self.tab_3)
        self.C_t.setMinimumSize(QtCore.QSize(400, 30))
        self.C_t.setMaximumSize(QtCore.QSize(400, 30))
        self.C_t.setObjectName("C_t")
        self.C_t.setValidator(validator)
        self.horizontalLayout_13.addWidget(self.C_t)
        self.label_24 = QtWidgets.QLabel(self.tab_3)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_13.addWidget(self.label_24)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_25 = QtWidgets.QLabel(self.tab_3)
        self.label_25.setMinimumSize(QtCore.QSize(0, 30))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_14.addWidget(self.label_25)
        self.phi = QtWidgets.QLineEdit(self.tab_3)
        self.phi.setMinimumSize(QtCore.QSize(400, 30))
        self.phi.setMaximumSize(QtCore.QSize(400, 30))
        self.phi.setObjectName("phi")
        self.phi.setValidator(validator)
        self.horizontalLayout_14.addWidget(self.phi)
        self.label_26 = QtWidgets.QLabel(self.tab_3)
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_14.addWidget(self.label_26)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_29 = QtWidgets.QLabel(self.tab_3)
        self.label_29.setMinimumSize(QtCore.QSize(0, 30))
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_16.addWidget(self.label_29)
        self.textEdit_15 = QtWidgets.QLineEdit(self.tab_3)
        self.textEdit_15.setMinimumSize(QtCore.QSize(400, 30))
        self.textEdit_15.setMaximumSize(QtCore.QSize(400, 30))
        self.textEdit_15.setObjectName("textEdit_15")
        self.textEdit_15.setValidator(validator)
        self.horizontalLayout_16.addWidget(self.textEdit_15)
        self.label_30 = QtWidgets.QLabel(self.tab_3)
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_16.addWidget(self.label_30)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_27 = QtWidgets.QLabel(self.tab_3)
        self.label_27.setMinimumSize(QtCore.QSize(0, 30))
        self.label_27.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_15.addWidget(self.label_27)
        self.P_initial = QtWidgets.QLineEdit(self.tab_3)
        self.P_initial.setMinimumSize(QtCore.QSize(400, 30))
        self.P_initial.setMaximumSize(QtCore.QSize(400, 30))
        self.P_initial.setObjectName("P_initial")
        self.P_initial.setValidator(validator)
        self.horizontalLayout_15.addWidget(self.P_initial)
        self.label_28 = QtWidgets.QLabel(self.tab_3)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_15.addWidget(self.label_28)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_12.addItem(spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.comboBox = QtWidgets.QComboBox(self.tab_4)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_12.addItem(spacerItem1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_2)
        self.horizontalLayout_7.addWidget(self.comboBox_3)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        self.verticalWidget_2 = QtWidgets.QWidget(self.tab_4)
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.verticalWidget_2)
        self.label_11.setObjectName("error_label")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.circle_radius = QtWidgets.QLineEdit(self.verticalWidget_2)
        self.circle_radius.setMinimumSize(QtCore.QSize(400, 30))
        self.circle_radius.setMaximumSize(QtCore.QSize(400, 30))
        self.circle_radius.setObjectName("circle_radius")
        self.circle_radius.setValidator(validator)
        self.horizontalLayout_10.addWidget(self.circle_radius)
        self.label_12 = QtWidgets.QLabel(self.verticalWidget_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.verticalLayout_12.addWidget(self.verticalWidget_2)
        self.verticalWidget_3 = QtWidgets.QWidget(self.tab_4)
        self.verticalWidget_3.setEnabled(True)
        self.verticalWidget_3.setMaximumSize(QtCore.QSize(199999, 199999))
        self.verticalWidget_3.setAutoFillBackground(False)
        self.verticalWidget_3.setObjectName("verticalWidget_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalWidget_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_43 = QtWidgets.QLabel(self.verticalWidget_3)
        self.label_43.setMinimumSize(QtCore.QSize(0, 30))
        self.label_43.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_23.addWidget(self.label_43)
        self.W_E_length = QtWidgets.QLineEdit(self.verticalWidget_3)
        self.W_E_length.setMinimumSize(QtCore.QSize(400, 30))
        self.W_E_length.setMaximumSize(QtCore.QSize(400, 30))
        self.W_E_length.setObjectName("W_E_length")
        self.W_E_length.setValidator(validator)
        self.horizontalLayout_23.addWidget(self.W_E_length)
        self.label_44 = QtWidgets.QLabel(self.verticalWidget_3)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_23.addWidget(self.label_44)
        self.verticalLayout_8.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_45 = QtWidgets.QLabel(self.verticalWidget_3)
        self.label_45.setMinimumSize(QtCore.QSize(0, 30))
        self.label_45.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_24.addWidget(self.label_45)
        self.N_S_length = QtWidgets.QLineEdit(self.verticalWidget_3)
        self.N_S_length.setMinimumSize(QtCore.QSize(400, 30))
        self.N_S_length.setMaximumSize(QtCore.QSize(400, 30))
        self.N_S_length.setObjectName("N_S_length")
        self.N_S_length.setValidator(validator)
        self.horizontalLayout_24.addWidget(self.N_S_length)
        self.label_46 = QtWidgets.QLabel(self.verticalWidget_3)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_24.addWidget(self.label_46)
        self.verticalLayout_8.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_47 = QtWidgets.QLabel(self.verticalWidget_3)
        self.label_47.setMinimumSize(QtCore.QSize(0, 30))
        self.label_47.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_25.addWidget(self.label_47)
        self.bound_1 = QtWidgets.QLineEdit(self.verticalWidget_3)
        self.bound_1.setMinimumSize(QtCore.QSize(400, 30))
        self.bound_1.setMaximumSize(QtCore.QSize(400, 30))
        self.bound_1.setObjectName("bound_1")
        self.bound_1.setValidator(validator)
        self.horizontalLayout_25.addWidget(self.bound_1)
        self.label_48 = QtWidgets.QLabel(self.verticalWidget_3)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_25.addWidget(self.label_48)
        self.verticalLayout_8.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_49 = QtWidgets.QLabel(self.verticalWidget_3)
        self.label_49.setMinimumSize(QtCore.QSize(0, 30))
        self.label_49.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_26.addWidget(self.label_49)
        self.bound_2 = QtWidgets.QLineEdit(self.verticalWidget_3)
        self.bound_2.setMinimumSize(QtCore.QSize(400, 30))
        self.bound_2.setMaximumSize(QtCore.QSize(400, 30))
        self.bound_2.setObjectName("bound_2")
        self.bound_2.setValidator(validator)
        self.horizontalLayout_26.addWidget(self.bound_2)
        self.label_50 = QtWidgets.QLabel(self.verticalWidget_3)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_26.addWidget(self.label_50)
        self.verticalLayout_8.addLayout(self.horizontalLayout_26)
        self.verticalLayout_12.addWidget(self.verticalWidget_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_12)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_5)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 750, 527))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_55 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_55.setMinimumSize(QtCore.QSize(0, 30))
        self.label_55.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_29.addWidget(self.label_55)
        self.vertical_position = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.vertical_position.setMinimumSize(QtCore.QSize(400, 30))
        self.vertical_position.setMaximumSize(QtCore.QSize(400, 30))
        self.vertical_position.setObjectName("vertical_position")
        self.vertical_position.setValidator(validator)
        self.horizontalLayout_29.addWidget(self.vertical_position)
        self.label_56 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_29.addWidget(self.label_56)
        self.verticalLayout_9.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_57 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_57.setMinimumSize(QtCore.QSize(0, 30))
        self.label_57.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_30.addWidget(self.label_57)
        self.vskritie_plasta = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.vskritie_plasta.setMinimumSize(QtCore.QSize(400, 30))
        self.vskritie_plasta.setMaximumSize(QtCore.QSize(400, 30))
        self.vskritie_plasta.setObjectName("vskritie_plasta")
        self.vskritie_plasta.setValidator(validator)
        self.horizontalLayout_30.addWidget(self.vskritie_plasta)
        self.label_58 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_30.addWidget(self.label_58)
        self.verticalLayout_9.addLayout(self.horizontalLayout_30)
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)



        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Радиус скважины"))
        self.label.setText(_translate("Dialog", "м"))
        self.label_3.setText(_translate("Dialog", "Длина горизонтальной или наклонной скважины"))
        self.label_5.setText(_translate("Dialog", "м"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Скважина"))
        self.label_4.setText(_translate("Dialog", "Объемный коэффициент"))
        self.label_9.setText(_translate("Dialog", "Вязкость"))
        self.label_10.setText(_translate("Dialog", "сП"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Флюид"))
        self.label_13.setText(_translate("Dialog", "Проницаемость "))
        self.Skin.setText(_translate("Dialog", "мД"))
        self.label_15.setText(_translate("Dialog", "Отн. верт. к гориз. прон  (kv/kh) "))
        self.label_23.setText(_translate("Dialog", "Общая сжимаемость"))
        self.label_24.setText(_translate("Dialog", "1/атм"))
        self.label_25.setText(_translate("Dialog", "Пористость"))
        self.label_29.setText(_translate("Dialog", "Скин-фактор"))
        self.label_27.setText(_translate("Dialog", "Начальное пластовое давление"))
        self.label_28.setText(_translate("Dialog", "атм"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Пласт"))


        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Геометрия"))

        self.label_7.setText(_translate("Dialog", "Форма границы"))
        self.comboBox.setItemText(0, _translate("Dialog", "Прямоугольная"))
        self.comboBox.setItemText(1, _translate("Dialog", "Круглая"))
        self.label_8.setText(_translate("Dialog", "Тип границы"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Замкнутая"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Пост. давление целиком (сссс)"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "Пост. давление Север и Юг (cncn)"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "Пост. давление Запад и Восток (ncnc)"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "Замкнутая"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "Пост. давление"))
        self.label_11.setText(_translate("Dialog", "Радиус окружности"))
        self.label_12.setText(_translate("Dialog", "м"))
        self.label_43.setText(_translate("Dialog", "Ширина прямоугольника (Запад - Восток)"))
        self.label_44.setText(_translate("Dialog", "м"))
        self.label_45.setText(_translate("Dialog", "Длина прямоугольника (Север - Юг)"))
        self.label_46.setText(_translate("Dialog", "м"))
        self.label_47.setText(_translate("Dialog", "Доля от ширины до центра"))
        self.label_48.setText(_translate("Dialog", "доли"))
        self.label_49.setText(_translate("Dialog", "Доля от длины до центра"))
        self.label_50.setText(_translate("Dialog", "доли"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Геометрия"))


        self.label_51.setText(_translate("Dialog", "Эффективная толщина пласта"))
        self.label_52.setText(_translate("Dialog", "м"))
        self.label_55.setText(_translate("Dialog", "Вертикальное положение (в долях от мощности)"))
        self.label_56.setText(_translate("Dialog", "доли"))
        self.label_57.setText(_translate("Dialog", "Величина вскрытия пласта (в долях от мощности)"))
        self.label_58.setText(_translate("Dialog", "доли"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "Ось Z"))
