# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parameters_1st_tab.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(600, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(600, 400))
        Dialog.setMaximumSize(QtCore.QSize(600, 400))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setScaledContents(False)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.textEdit_4 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_4.setMinimumSize(QtCore.QSize(60, 30))
        self.textEdit_4.setMaximumSize(QtCore.QSize(60, 30))
        self.textEdit_4.setObjectName("textEdit_4")
        self.horizontalLayout_4.addWidget(self.textEdit_4)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setMinimumSize(QtCore.QSize(50, 0))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setIndent(10)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setScaledContents(False)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.textEdit_5 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_5.setMinimumSize(QtCore.QSize(60, 30))
        self.textEdit_5.setMaximumSize(QtCore.QSize(60, 30))
        self.textEdit_5.setObjectName("textEdit_5")
        self.horizontalLayout_5.addWidget(self.textEdit_5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setMinimumSize(QtCore.QSize(50, 0))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setWordWrap(True)
        self.label_10.setIndent(10)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setScaledContents(False)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("error_label")
        self.horizontalLayout_6.addWidget(self.label_11)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.textEdit_6 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_6.setMinimumSize(QtCore.QSize(60, 30))
        self.textEdit_6.setMaximumSize(QtCore.QSize(60, 30))
        self.textEdit_6.setObjectName("textEdit_6")
        self.horizontalLayout_6.addWidget(self.textEdit_6)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setMinimumSize(QtCore.QSize(50, 0))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setWordWrap(True)
        self.label_12.setIndent(10)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setScaledContents(False)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.textEdit_7 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_7.setMinimumSize(QtCore.QSize(60, 30))
        self.textEdit_7.setMaximumSize(QtCore.QSize(60, 30))
        self.textEdit_7.setObjectName("textEdit_7")
        self.horizontalLayout_7.addWidget(self.textEdit_7)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem14)
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setMinimumSize(QtCore.QSize(50, 0))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setWordWrap(True)
        self.label_14.setIndent(10)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem15)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem16)
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setScaledContents(False)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem17)
        self.textEdit_8 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_8.setMinimumSize(QtCore.QSize(60, 30))
        self.textEdit_8.setMaximumSize(QtCore.QSize(60, 30))
        self.textEdit_8.setObjectName("textEdit_8")
        self.horizontalLayout_8.addWidget(self.textEdit_8)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem18)
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setMinimumSize(QtCore.QSize(50, 0))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setWordWrap(True)
        self.label_16.setIndent(10)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem19)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem20)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem21)
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setScaledContents(False)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_9.addWidget(self.label_17)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem22)
        self.textEdit_9 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_9.setMinimumSize(QtCore.QSize(60, 30))
        self.textEdit_9.setMaximumSize(QtCore.QSize(60, 30))
        self.textEdit_9.setObjectName("textEdit_9")
        self.horizontalLayout_9.addWidget(self.textEdit_9)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem23)
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setMinimumSize(QtCore.QSize(50, 0))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setWordWrap(True)
        self.label_18.setIndent(10)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_9.addWidget(self.label_18)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem24)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem25)
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setScaledContents(False)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_10.addWidget(self.label_19)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem26)
        self.textEdit_10 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_10.setMinimumSize(QtCore.QSize(60, 30))
        self.textEdit_10.setMaximumSize(QtCore.QSize(60, 30))
        self.textEdit_10.setObjectName("textEdit_10")
        self.horizontalLayout_10.addWidget(self.textEdit_10)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem27)
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setMinimumSize(QtCore.QSize(50, 0))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setWordWrap(True)
        self.label_20.setIndent(10)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_10.addWidget(self.label_20)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem28)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem29)
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setScaledContents(False)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_11.addWidget(self.label_21)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem30)
        self.textEdit_11 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_11.setMinimumSize(QtCore.QSize(60, 30))
        self.textEdit_11.setMaximumSize(QtCore.QSize(60, 30))
        self.textEdit_11.setObjectName("textEdit_11")
        self.horizontalLayout_11.addWidget(self.textEdit_11)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem31)
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setMinimumSize(QtCore.QSize(50, 0))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setWordWrap(True)
        self.label_22.setIndent(10)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_11.addWidget(self.label_22)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem32)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem33)
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setScaledContents(False)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_12.addWidget(self.label_23)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem34)
        self.textEdit_12 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_12.setMinimumSize(QtCore.QSize(60, 30))
        self.textEdit_12.setMaximumSize(QtCore.QSize(60, 30))
        self.textEdit_12.setObjectName("textEdit_12")
        self.horizontalLayout_12.addWidget(self.textEdit_12)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem35)
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setMinimumSize(QtCore.QSize(50, 0))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setWordWrap(True)
        self.label_24.setIndent(10)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_12.addWidget(self.label_24)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem36)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem37)
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setScaledContents(False)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_13.addWidget(self.label_25)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem38)
        self.textEdit_13 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_13.setMinimumSize(QtCore.QSize(60, 30))
        self.textEdit_13.setMaximumSize(QtCore.QSize(60, 30))
        self.textEdit_13.setObjectName("textEdit_13")
        self.horizontalLayout_13.addWidget(self.textEdit_13)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem39)
        self.label_26 = QtWidgets.QLabel(Dialog)
        self.label_26.setMinimumSize(QtCore.QSize(50, 0))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setWordWrap(True)
        self.label_26.setIndent(10)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_13.addWidget(self.label_26)
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem40)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem41)
        self.label_27 = QtWidgets.QLabel(Dialog)
        self.label_27.setScaledContents(False)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_14.addWidget(self.label_27)
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem42)
        self.textEdit_14 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_14.setMinimumSize(QtCore.QSize(60, 30))
        self.textEdit_14.setMaximumSize(QtCore.QSize(60, 30))
        self.textEdit_14.setObjectName("textEdit_14")
        self.horizontalLayout_14.addWidget(self.textEdit_14)
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem43)
        self.label_28 = QtWidgets.QLabel(Dialog)
        self.label_28.setMinimumSize(QtCore.QSize(50, 0))
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setWordWrap(True)
        self.label_28.setIndent(10)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_14.addWidget(self.label_28)
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem44)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem45 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem45)
        self.label_29 = QtWidgets.QLabel(Dialog)
        self.label_29.setScaledContents(False)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_15.addWidget(self.label_29)
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem46)
        self.textEdit_15 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_15.setMinimumSize(QtCore.QSize(60, 30))
        self.textEdit_15.setMaximumSize(QtCore.QSize(60, 30))
        self.textEdit_15.setObjectName("textEdit_15")
        self.horizontalLayout_15.addWidget(self.textEdit_15)
        spacerItem47 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem47)
        self.label_30 = QtWidgets.QLabel(Dialog)
        self.label_30.setMinimumSize(QtCore.QSize(50, 0))
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setWordWrap(True)
        self.label_30.setIndent(10)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_15.addWidget(self.label_30)
        spacerItem48 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem48)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem49 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem49)
        self.label_31 = QtWidgets.QLabel(Dialog)
        self.label_31.setScaledContents(False)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_16.addWidget(self.label_31)
        spacerItem50 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem50)
        self.textEdit_16 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_16.setMinimumSize(QtCore.QSize(60, 30))
        self.textEdit_16.setMaximumSize(QtCore.QSize(60, 30))
        self.textEdit_16.setObjectName("textEdit_16")
        self.horizontalLayout_16.addWidget(self.textEdit_16)
        spacerItem51 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem51)
        self.label_32 = QtWidgets.QLabel(Dialog)
        self.label_32.setMinimumSize(QtCore.QSize(50, 0))
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setWordWrap(True)
        self.label_32.setIndent(10)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_16.addWidget(self.label_32)
        spacerItem52 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem52)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem53 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem53)
        self.label_33 = QtWidgets.QLabel(Dialog)
        self.label_33.setScaledContents(False)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_17.addWidget(self.label_33)
        spacerItem54 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem54)
        self.textEdit_17 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_17.setMinimumSize(QtCore.QSize(60, 30))
        self.textEdit_17.setMaximumSize(QtCore.QSize(60, 30))
        self.textEdit_17.setObjectName("textEdit_17")
        self.horizontalLayout_17.addWidget(self.textEdit_17)
        spacerItem55 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem55)
        self.label_34 = QtWidgets.QLabel(Dialog)
        self.label_34.setMinimumSize(QtCore.QSize(50, 0))
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setWordWrap(True)
        self.label_34.setIndent(10)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_17.addWidget(self.label_34)
        spacerItem56 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem56)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem57 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem57)
        self.label_35 = QtWidgets.QLabel(Dialog)
        self.label_35.setScaledContents(False)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_18.addWidget(self.label_35)
        spacerItem58 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem58)
        self.textEdit_18 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_18.setMinimumSize(QtCore.QSize(60, 30))
        self.textEdit_18.setMaximumSize(QtCore.QSize(60, 30))
        self.textEdit_18.setObjectName("textEdit_18")
        self.horizontalLayout_18.addWidget(self.textEdit_18)
        spacerItem59 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem59)
        self.label_36 = QtWidgets.QLabel(Dialog)
        self.label_36.setMinimumSize(QtCore.QSize(50, 0))
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setWordWrap(True)
        self.label_36.setIndent(10)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_18.addWidget(self.label_36)
        spacerItem60 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem60)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem61 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem61)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.ok_cancel_btn = QtWidgets.QDialogButtonBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok_cancel_btn.sizePolicy().hasHeightForWidth())
        self.ok_cancel_btn.setSizePolicy(sizePolicy)
        self.ok_cancel_btn.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.ok_cancel_btn.setCenterButtons(True)
        self.ok_cancel_btn.setObjectName("ok_cancel_btn")
        self.verticalLayout_4.addWidget(self.ok_cancel_btn)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


        self.ok_cancel_btn.accepted.connect(self.test)
        self.ok_cancel_btn.rejected.connect(Dialog.close)

    def test():
        print(50)





    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_7.setText(_translate("Dialog", "K = "))
        self.label_8.setText(_translate("Dialog", "мД"))
        self.label_9.setText(_translate("Dialog", "K = "))
        self.label_10.setText(_translate("Dialog", "мД"))
        self.label_11.setText(_translate("Dialog", "K = "))
        self.label_12.setText(_translate("Dialog", "мД"))
        self.label_13.setText(_translate("Dialog", "K = "))
        self.label_14.setText(_translate("Dialog", "мД"))
        self.label_15.setText(_translate("Dialog", "K = "))
        self.label_16.setText(_translate("Dialog", "мД"))
        self.label_17.setText(_translate("Dialog", "K = "))
        self.label_18.setText(_translate("Dialog", "мД"))
        self.label_19.setText(_translate("Dialog", "K = "))
        self.label_20.setText(_translate("Dialog", "мД"))
        self.label_21.setText(_translate("Dialog", "K = "))
        self.label_22.setText(_translate("Dialog", "мД"))
        self.label_23.setText(_translate("Dialog", "K = "))
        self.label_24.setText(_translate("Dialog", "мД"))
        self.label_25.setText(_translate("Dialog", "K = "))
        self.label_26.setText(_translate("Dialog", "мД"))
        self.label_27.setText(_translate("Dialog", "K = "))
        self.label_28.setText(_translate("Dialog", "мД"))
        self.label_29.setText(_translate("Dialog", "K = "))
        self.label_30.setText(_translate("Dialog", "мД"))
        self.label_31.setText(_translate("Dialog", "K = "))
        self.label_32.setText(_translate("Dialog", "мД"))
        self.label_33.setText(_translate("Dialog", "K = "))
        self.label_34.setText(_translate("Dialog", "мД"))
        self.label_35.setText(_translate("Dialog", "K = "))
        self.label_36.setText(_translate("Dialog", "мД"))