# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Common_parameters_UI_v3.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Common_prmrs(object):
    def setupUi(self, Common_prmrs):
        Common_prmrs.setObjectName("Common_prmrs")
        Common_prmrs.resize(772, 610)

        regExp = QtCore.QRegExp("[-]{0,1}\d{0,}\.\d{0,}")  # Валидатор на ввод только чисел и точки(используется для полей ввода)
        validator = QtGui.QRegExpValidator(regExp)

        self.verticalLayout = QtWidgets.QVBoxLayout(Common_prmrs)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Common_prmrs)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.porosity = QtWidgets.QLineEdit(self.tab)
        self.porosity.setMinimumSize(QtCore.QSize(400, 30))
        self.porosity.setMaximumSize(QtCore.QSize(400, 30))
        self.porosity.setObjectName("porosity")
        self.porosity.setValidator(validator)
        self.horizontalLayout_3.addWidget(self.porosity)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setText("доли")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setMinimumSize(QtCore.QSize(0, 30))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.h_eff = QtWidgets.QLineEdit(self.tab)
        self.h_eff.setMinimumSize(QtCore.QSize(400, 30))
        self.h_eff.setMaximumSize(QtCore.QSize(400, 30))
        self.h_eff.setObjectName("h_eff")
        self.h_eff.setValidator(validator)
        self.horizontalLayout_5.addWidget(self.h_eff)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.rc = QtWidgets.QLineEdit(self.tab)
        self.rc.setMinimumSize(QtCore.QSize(400, 30))
        self.rc.setMaximumSize(QtCore.QSize(400, 30))
        self.rc.setObjectName("rc")
        self.rc.setValidator(validator)
        self.horizontalLayout.addWidget(self.rc)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setMinimumSize(QtCore.QSize(0, 30))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.mu = QtWidgets.QLineEdit(self.tab_2)
        self.mu.setMinimumSize(QtCore.QSize(400, 30))
        self.mu.setMaximumSize(QtCore.QSize(400, 30))
        self.mu.setObjectName("mu")
        self.mu.setValidator(validator)
        self.horizontalLayout_6.addWidget(self.mu)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_31 = QtWidgets.QLabel(self.tab_2)
        self.label_31.setMinimumSize(QtCore.QSize(0, 30))
        self.label_31.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_17.addWidget(self.label_31)
        self.C_t = QtWidgets.QLineEdit(self.tab_2)
        self.C_t.setMinimumSize(QtCore.QSize(400, 30))
        self.C_t.setMaximumSize(QtCore.QSize(400, 30))
        self.C_t.setObjectName("C_t")
        self.C_t.setValidator(validator)
        self.horizontalLayout_17.addWidget(self.C_t)
        self.label_32 = QtWidgets.QLabel(self.tab_2)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_17.addWidget(self.label_32)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.B_liq = QtWidgets.QLineEdit(self.tab_2)
        self.B_liq.setMinimumSize(QtCore.QSize(400, 30))
        self.B_liq.setMaximumSize(QtCore.QSize(400, 30))
        self.B_liq.setObjectName("B_liq")
        self.B_liq.setValidator(validator)
        self.horizontalLayout_4.addWidget(self.B_liq)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setText("м3/м3")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.error_label = QtWidgets.QLabel(Common_prmrs)   # Лейбл оповещения о неверном вводе параметров
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.error_label.setFont(font)
        f = open('Design/Error_label_style.py', 'r')  # Применение стиля
        self.Error_style = f.read()
        f.close()
        self.error_label.setStyleSheet(self.Error_style)
        self.error_label.setTextFormat(QtCore.Qt.AutoText)
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setObjectName("error_label")
        self.verticalLayout.addWidget(self.error_label)

        self.buttonBox = QtWidgets.QDialogButtonBox(Common_prmrs)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Common_prmrs)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Common_prmrs)

    def retranslateUi(self, Common_prmrs):
        _translate = QtCore.QCoreApplication.translate
        Common_prmrs.setWindowTitle(_translate("Common_prmrs", "Общие параметры"))
        self.label_3.setText(_translate("Common_prmrs", "Пористость"))
        self.label_7.setText(_translate("Common_prmrs", "Эффективная толщина пласта"))
        self.label_8.setText(_translate("Common_prmrs", "м"))
        self.label_2.setText(_translate("Common_prmrs", "Радиус скважины"))
        self.label.setText(_translate("Common_prmrs", "м"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Common_prmrs", "Скважина и пласт"))
        self.label_9.setText(_translate("Common_prmrs", "Вязкость"))
        self.label_10.setText(_translate("Common_prmrs", "сП"))
        self.label_31.setText(_translate("Common_prmrs", "Общая сжимаемость"))
        self.label_32.setText(_translate("Common_prmrs", "1/атм"))
        self.label_4.setText(_translate("Common_prmrs", "Объемный коэффициент"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Common_prmrs", "Флюид"))
        self.error_label.setText(_translate("Common_prmrs", "Ошибка! Проверьте введённые параметры."))

