# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Model_prmrs_UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Model_prmrs(object):
    def setupUi(self, Model_prmrs):
        Model_prmrs.setObjectName("Model_prmrs")
        Model_prmrs.resize(900, 800)

        regExp = QtCore.QRegExp("[-]{0,1}\d{0,}\.\d{0,}")  # Валидатор на ввод только чисел и точки(используется для полей ввода)
        validator = QtGui.QRegExpValidator(regExp)

        self.verticalLayout = QtWidgets.QVBoxLayout(Model_prmrs)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.well_type_combo = QtWidgets.QComboBox()
        self.well_type_combo.setObjectName("well_type_combo")
        self.well_type_combo.addItem("")
        self.well_type_combo.addItem("")
        self.well_type_combo.addItem("")
        self.well_type_combo.addItem("")
        self.label_1 = QtWidgets.QLabel(Model_prmrs)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout_4.addWidget(self.label_1)
        self.horizontalLayout_4.addWidget(self.well_type_combo)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(Model_prmrs)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.comboBox = QtWidgets.QComboBox(Model_prmrs)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        # self.comboBox.addItem("")     # В дальнейшем здесь будет круговая граница
        self.horizontalLayout_5.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(Model_prmrs)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.comboBox_2 = QtWidgets.QComboBox(Model_prmrs)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_2)
        self.comboBox_3 = QtWidgets.QComboBox(Model_prmrs)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.widget_2 = QtWidgets.QWidget(Model_prmrs)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.widget_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.circle_radius = QtWidgets.QLineEdit(self.widget_2)
        self.circle_radius.setObjectName("circle_radius")
        self.circle_radius.setValidator(validator)
        self.horizontalLayout_11.addWidget(self.circle_radius)
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_11.addWidget(self.label)
        self.verticalLayout.addWidget(self.widget_2)
        self.verticalWidget_3 = QtWidgets.QWidget(Model_prmrs)
        self.verticalWidget_3.setEnabled(True)
        self.verticalWidget_3.setMaximumSize(QtCore.QSize(199999, 199999))
        self.verticalWidget_3.setAutoFillBackground(False)
        self.verticalWidget_3.setObjectName("verticalWidget_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalWidget_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_43 = QtWidgets.QLabel(self.verticalWidget_3)
        self.label_43.setMinimumSize(QtCore.QSize(0, 30))
        self.label_43.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_23.addWidget(self.label_43)
        self.W_E_length = QtWidgets.QLineEdit(self.verticalWidget_3)
        self.W_E_length.setObjectName("W_E_length")
        self.W_E_length.setValidator(validator)
        self.horizontalLayout_23.addWidget(self.W_E_length)
        self.label_44 = QtWidgets.QLabel(self.verticalWidget_3)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_23.addWidget(self.label_44)
        self.verticalLayout_8.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_45 = QtWidgets.QLabel(self.verticalWidget_3)
        self.label_45.setMinimumSize(QtCore.QSize(0, 30))
        self.label_45.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_24.addWidget(self.label_45)
        self.N_S_length = QtWidgets.QLineEdit(self.verticalWidget_3)
        self.N_S_length.setObjectName("N_S_length")
        self.N_S_length.setValidator(validator)
        self.horizontalLayout_24.addWidget(self.N_S_length)
        self.label_46 = QtWidgets.QLabel(self.verticalWidget_3)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_24.addWidget(self.label_46)
        self.verticalLayout_8.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_47 = QtWidgets.QLabel(self.verticalWidget_3)
        self.label_47.setMinimumSize(QtCore.QSize(0, 30))
        self.label_47.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_25.addWidget(self.label_47)
        self.width_of_center = QtWidgets.QLineEdit(self.verticalWidget_3)
        self.width_of_center.setObjectName("width_of_center")
        self.width_of_center.setValidator(validator)
        self.horizontalLayout_25.addWidget(self.width_of_center)
        self.label_48 = QtWidgets.QLabel(self.verticalWidget_3)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_25.addWidget(self.label_48)
        self.verticalLayout_8.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_49 = QtWidgets.QLabel(self.verticalWidget_3)
        self.label_49.setMinimumSize(QtCore.QSize(0, 30))
        self.label_49.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_26.addWidget(self.label_49)
        self.length_of_center = QtWidgets.QLineEdit(self.verticalWidget_3)
        self.length_of_center.setObjectName("length_of_center")
        self.length_of_center.setValidator(validator)
        self.horizontalLayout_26.addWidget(self.length_of_center)
        self.label_50 = QtWidgets.QLabel(self.verticalWidget_3)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_26.addWidget(self.label_50)
        self.verticalLayout_8.addLayout(self.horizontalLayout_26)
        self.verticalLayout.addWidget(self.verticalWidget_3)
        self.tableWidget = QtWidgets.QTableWidget(Model_prmrs)
        self.tableWidget.setObjectName("tableWidget")
        self.verticalLayout.addWidget(self.tableWidget)

        self.error_label = QtWidgets.QLabel(Model_prmrs)  # Лейбл оповещения о неверном вводе параметров
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.error_label.setFont(font)
        f = open('Design/Error_label_style.py', 'r')  # Применение стиля
        self.Error_style = f.read()
        f.close()
        self.error_label.setStyleSheet(self.Error_style)
        self.error_label.setTextFormat(QtCore.Qt.AutoText)
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setObjectName("error_label")
        self.verticalLayout.addWidget(self.error_label)

        self.buttonBox = QtWidgets.QDialogButtonBox(Model_prmrs)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Model_prmrs)
        QtCore.QMetaObject.connectSlotsByName(Model_prmrs)

    def retranslateUi(self, Model_prmrs):
        _translate = QtCore.QCoreApplication.translate
        Model_prmrs.setWindowTitle(_translate("Model_prmrs", "Параметры модели"))
        self.label_7.setText(_translate("Model_prmrs", "Форма границы"))
        self.comboBox.setItemText(0, _translate("Model_prmrs", "Прямоугольная"))
        # self.comboBox.setItemText(1, _translate("Model_prmrs", "Круглая"))
        self.label_8.setText(_translate("Model_prmrs", "Тип границы"))
        self.comboBox_2.setItemText(0, _translate("Model_prmrs", "Замкнутая"))
        self.comboBox_2.setItemText(1, _translate("Model_prmrs", "Пост. давление целиком (сссс)"))
        self.comboBox_2.setItemText(2, _translate("Model_prmrs", "Пост. давление Север и Юг (cncn)"))
        self.comboBox_2.setItemText(3, _translate("Model_prmrs", "Пост. давление Запад и Восток (ncnc)"))
        self.comboBox_3.setItemText(0, _translate("Model_prmrs", "Замкнутая"))
        self.comboBox_3.setItemText(1, _translate("Model_prmrs", "Пост. давление"))
        self.label_12.setText(_translate("Model_prmrs", "Радиус окружности"))
        self.label.setText(_translate("Model_prmrs", "м"))
        self.label_43.setText(_translate("Model_prmrs", "Длина прямоугольника"))
        self.label_44.setText(_translate("Model_prmrs", "м"))
        self.label_45.setText(_translate("Model_prmrs", "Ширина прямоугольника(сонаправлена с ГС)"))
        self.label_46.setText(_translate("Model_prmrs", "м"))
        self.label_47.setText(_translate("Model_prmrs", "Доля от ширины до центра"))
        self.label_48.setText(_translate("Model_prmrs", "доли"))
        self.label_49.setText(_translate("Model_prmrs", "Доля от длины до центра"))
        self.label_50.setText(_translate("Model_prmrs", "доли"))
        self.label_1.setText(_translate("Model_prmrs", "Тип скважины"))
        self.well_type_combo.setItemText(0, _translate("Model_prmrs", "Вертикальная скважина"))
        self.well_type_combo.setItemText(1, _translate("Model_prmrs", "Горизонтальная скважина"))
        self.well_type_combo.setItemText(2, _translate("Model_prmrs", "ГРП"))
        self.well_type_combo.setItemText(3, _translate("Model_prmrs", "ГС с МГРП"))
        self.error_label.setText(_translate("Model_prmrs", "Ошибка! Проверьте введённые параметры."))
